//los types siempre se escriben en mayuscula
export const FORMULARIO_MATERIA = 'FORMULARIO_MATERIA';
export const OBTENER_MATERIAS = 'OBTENER_MATERIAS';
export const AGREGAR_MATERIA = 'AGREGAR_MATERIA';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const MATERIA_ACTUAL = 'MATERIA_ACTUAL';
export const ELIMINAR_MATERIA = 'ELIMINAR_MATERIA';

//tareas
export const  SELECCIONAR_TAREAS = 'SELECCIONAR_TAREAS';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const VALIDAR_TAREA = 'VALIDAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const MODIFICAR_TAREA = 'MODIFICAR_TAREA';
export const ESTADO_TAREA = 'ESTADO_TAREA';
export const TAREA_A_MODIFICAR = 'TAREA_A_MODIFICAR';


