export const NUEVO_LIBRO = 'NUEVO_LIBRO';
export const NUEVO_LIBRO_EXITO = 'NUEVO_LIBRO_EXITO';
export const NUEVO_LIBRO_ERROR = 'NUEVO_LIBRO_ERROR';

export const LISTADO_LIBROS = 'LISTADO_LIBROS';
export const DESCARGA_LIBROS_EXITO = 'LISTADO_LIBROS_EXITO';
export const DESCARGA_LIBROS_ERROR = 'DESCARGA_LIBROS_ERROR';

export const OBTENER_LIBRO_ELIMINAR = 'OBTENER_LIBRO_ELIMINAR';
export const LIBRO_ELIMINADO_EXITO = 'LIBRO_ELIMINADO_EXITO';
export const LIBRO_ELIMINADO_ERROR = 'LIBRO_ELIMINADO_ERROR';

export const OBTENER_LIBRO_EDITAR = 'OBTENER_LIBRO_EDITAR';
export const COMENZAR_EDICION_LIBRO = 'COMENZAR_EDICION_LIBRO';
export const LIBRO_EDITADO_EXITO = 'LIBRO_EDITADO_EXITO';
export const LIBRO_EDITADO_ERROR = 'LIBRO_EDITADO_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';